--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/TobyDev265/BedrockUnicodeCharacters
build-by-default: true
branches:
- main
projects:
  BedrockUnicodeCharacters:
    path: ""
    model: virion
    type: library
...
